// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGM.Infraestructure.Data;

namespace SGM.Infraestructure.Migrations
{
    [DbContext(typeof(SGMContext))]
    [Migration("20181129003453_ClasseMarcaAdicionada")]
    partial class ClasseMarcaAdicionada
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGM.ApplicationCore.Entity.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descrição");

                    b.HasKey("MarcaId");

                    b.ToTable("TbMarcas");
                });

            modelBuilder.Entity("SGM.ApplicationCore.Entity.Multa", b =>
                {
                    b.Property<int>("MultaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Pontuação");

                    b.Property<int>("Valor");

                    b.Property<int?>("VeiculosVeiculoId");

                    b.HasKey("MultaId");

                    b.HasIndex("VeiculosVeiculoId");

                    b.ToTable("TbInfração");
                });

            modelBuilder.Entity("SGM.ApplicationCore.Veiculo", b =>
                {
                    b.Property<int>("VeiculoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MarcasMarcaId");

                    b.Property<string>("Placa");

                    b.Property<string>("Renavam");

                    b.HasKey("VeiculoId");

                    b.HasIndex("MarcasMarcaId");

                    b.ToTable("TbVeiculos");
                });

            modelBuilder.Entity("SGM.ApplicationCore.Entity.Multa", b =>
                {
                    b.HasOne("SGM.ApplicationCore.Veiculo", "Veiculos")
                        .WithMany()
                        .HasForeignKey("VeiculosVeiculoId");
                });

            modelBuilder.Entity("SGM.ApplicationCore.Veiculo", b =>
                {
                    b.HasOne("SGM.ApplicationCore.Entity.Marca", "Marcas")
                        .WithMany("Veiculo")
                        .HasForeignKey("MarcasMarcaId");
                });
#pragma warning restore 612, 618
        }
    }
}
